### ISSUE TITLE
How to run this project locally? 

### ISSUE THREAD

**Issue by surajsubudhi10** [johan-akerman/SpotifyTranscripts#1]
I really loved the idea behind this project. I want to run it locally on my machine.
I'm able to run the frontend part. As I have no experience with flask, Can you mention the steps for running the project's backend?

**Comment by johan-akerman** [comment]
Hi Suraj, I am glad you liked it! 
I have added a section in the readme on how to run the frontend and backend now. Hope this helps!

**Comment by surajsubudhi10** [comment]
Thanks for adding the section. Do we need to set up any extra thing for SQLite?

I'm getting the following error 

```
127.0.0.1 - - [09/Jan/2023 19:49:31] "GET /get_podcast?url=https://p.scdn.co/mp3-preview/e6a887032397b93e62d06425e1fcdecfb700160c HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/suraj/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/suraj/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: podcast

```

**Comment by surajsubudhi10** [comment]
Sorry, It was a mistake on my side. Closing the issue as I'm able to run app.
