### ISSUE TITLE
INVALID CLIENT 

### ISSUE THREAD

**Issue by b-RAYO** [johan-akerman/SpotifyTranscripts#3]
Hey I'm have everything setup but I'm getting "invalid_client" when I try to log in to my account.

**Comment by d4nh5u** [comment]
I also encountered the same issue when trying to "log in with Spotify", and received an "INVALID CLIENT" error.

**Comment by tnhoang** [comment]
Follow this guys https://support.heateor.com/get-spotify-client-id-client-secret/

**Comment by b-RAYO** [comment]
@tnhoang Thanks I got it to work.
